//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdPosting_QRONYKEntities : DbContext
    {
        public AdPosting_QRONYKEntities()
            : base("name=AdPosting_QRONYKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Comments_Deals_Master> Comments_Deals_Master { get; set; }
        public DbSet<Comments_Laws_Master> Comments_Laws_Master { get; set; }
        public DbSet<Comments_News_Master> Comments_News_Master { get; set; }
        public DbSet<Comments_Treading_Master> Comments_Treading_Master { get; set; }
        public DbSet<DealsMaster> DealsMasters { get; set; }
        public DbSet<LawsMaster> LawsMasters { get; set; }
        public DbSet<NewsMaster> NewsMasters { get; set; }
        public DbSet<TreadingMaster> TreadingMasters { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
